
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author 6
 */
public class RESET_PASS extends javax.swing.JFrame {


    /** Creates new form RESET_PASS */
    public RESET_PASS() {
        initComponents();
T3.setVisible(false);
        T4.setVisible(false);
        T5.setVisible(false);
        P1.setVisible(false);
        B1.setVisible(false);
        B2.setVisible(false);
        L1.setVisible(false);
        L2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        T3 = new javax.swing.JPasswordField();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        T4 = new javax.swing.JPasswordField();
        P1 = new javax.swing.JProgressBar();
        T5 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        T2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        C1 = new javax.swing.JComboBox();
        T1 = new javax.swing.JTextField();
        B3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("ENTER  PASSWORD");

        T3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                T3CaretUpdate(evt);
            }
        });

        L1.setText("ENTER NEW PASSWORD");

        L2.setText("CONFIRM NEW PASSWORD");

        B1.setText("CHANGE PASSWORD");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setText("CANCEL");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        jButton3.setText("CONFIRM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Security Question");

        jLabel5.setText("ENTER  ANSWER");

        jLabel6.setText("Select User ID");

        C1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                C1ItemStateChanged(evt);
            }
        });

        T1.setEditable(false);

        B3.setText("CANCEL");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(L1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(T3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(T5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(T1)
                                    .addComponent(C1, 0, 161, Short.MAX_VALUE))))))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B1)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(B3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L1)
                                .addGap(29, 29, 29)
                                .addComponent(L2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B2)
                            .addComponent(B1))
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_T3CaretUpdate
        // TODO add your handling code here:
         int i=T3.getText().length();
        if(i<=3)
        {P1.setValue(i*10);P1.setForeground(Color.RED);T5.setText("TOO WEAK");}
        else if(i<=5)
        {P1.setValue(i*10);P1.setForeground(Color.YELLOW);T5.setText("CAN BE BETTER");}
        else if(i>=8)
        {P1.setValue(100);P1.setForeground(Color.GREEN);T5.setText("READY TO GO");}
}//GEN-LAST:event_T3CaretUpdate

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.DriverManager");
            Connection C=DriverManager.getConnection("jdbc:mysql://localhost:3306/RETAIL","root","QWERTY");
            Statement S = C.createStatement();
            String q="update user_info set password='"+T3.getText()+"' where user_id="+C1.getSelectedItem()+";";
            String q1="update users set pass='"+T3.getText()+"' where user_id="+C1.getSelectedItem()+";";
            if (T4.getText().equals("") || T3.getText().equals(""))
            {
            JOptionPane.showMessageDialog(this, "Enter Values in all fields");
            }
            else
            {
                S.executeUpdate(q);
                S.executeUpdate(q1);
                this.dispose();
           }
        } catch(HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         JOptionPane.showMessageDialog(this, "Password changed");
         
}//GEN-LAST:event_B1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       try {
            Class.forName("java.sql.DriverManager");
            Connection C=DriverManager.getConnection("jdbc:mysql://localhost:3306/RETAIL","root","QWERTY");
            Statement S = C.createStatement();
            String q="select user_id from user_info ;";
            ResultSet RS=S.executeQuery(q);
        while(RS.next())
        {
        String UID =RS.getString("user_id");
        C1.addItem(UID);
        }
       }
         catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.DriverManager");
            Connection C=DriverManager.getConnection("jdbc:mysql://localhost:3306/RETAIL","root","QWERTY");
            Statement S = C.createStatement();
           String q="select answer from user_info WHERE user_id="+C1.getSelectedItem()+";";
         ResultSet RS=S.executeQuery(q);
        RS.first();
        String answr=RS.getString("answer");
       if(T2.getText().equals(""))
       {
       JOptionPane.showMessageDialog(this, "Please Enter Answer");
       }
        if (answr.equals(T2.getText()))
        {
        T3.setVisible(true);
        T4.setVisible(true);
        T5.setVisible(true);
        P1.setVisible(true);
        B1.setVisible(true);
        B2.setVisible(true);
        L1.setVisible(true);
        L2.setVisible(true);
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Enter Correct Answer");
        }
        }

            catch(HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void C1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_C1ItemStateChanged
        // TODO add your handling code here:
         try {
            Class.forName("java.sql.DriverManager");
            Connection C=DriverManager.getConnection("jdbc:mysql://localhost:3306/RETAIL","root","QWERTY");
            Statement S = C.createStatement();
            String q="select security_question from user_info where user_id="+C1.getSelectedItem()+";";
            ResultSet RS=S.executeQuery(q);
       RS.first();
       String qustn = RS.getString("security_question");
       T1.setText(qustn);
     }
        catch(ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
}//GEN-LAST:event_C1ItemStateChanged

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new First().setVisible(true);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new First().setVisible(true);
    }//GEN-LAST:event_B3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RESET_PASS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JComboBox C1;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JProgressBar P1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JPasswordField T3;
    private javax.swing.JPasswordField T4;
    private javax.swing.JLabel T5;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
